//> using scala "3.3.1"
//> using dep "com.lihaoyi::upickle:4.1.0"
//> using dep "com.github.scopt::scopt:4.0.1"
//> using dep "org.slf4j:slf4j-api:1.7.36"
//> using dep "ch.qos.logback:logback-classic:1.2.11"
//> using dep "org.locationtech.jts:jts-core:1.20.0"
//> using test.dep "org.scalameta::munit::0.7.29"